# Configuration for automated dependency updates using Dependabot
version: 2
updates:
  # Define the target package ecosystem
  - package-ecosystem: "npm"
    # Specify the root directory
    directory: "/"
    # Schedule automated updates to run weekly
    schedule:
      interval: "weekly"
    # Labels to apply to Dependabot PRs
    labels:
      - "dependencies"
    # Specify the target branch for PRs
    target-branch: "develop"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
    # Customize commit message prefix
    commit-message:
      prefix: "chore(deps):"
